FROM node:14-alpine

ENV PY_DOLLAR_TO_SHEKEL_PORT=3000
ENV PY_EURO_TO_SHEKEL_PORT=3001
ENV JS_HANDLER_PORT=3002

WORKDIR /usr/src/app

COPY JS/main_js_handler.js .
COPY *.json .

RUN npm install

EXPOSE ${JS_HANDLER_PORT}

CMD ["node", "main_js_handler.js"]
